auto_register:
  - ./example/yolov12/module/module.yaml

SimpleCNN:
  imports: [from test_converter import converter]
  args: [in_ch, class_num]
  layers:
    - [-1, C2f, [in_ch, 16]]
    - [-1, C2f, [16, 32]]
    - [-1, C2f, [32, 64]]
    # - [-1, C2f, [64, 128]]
    # - [-1, C2f, [128, 256]]
    # - [-1, C2f, [256, 512]]
